### ISSUE TITLE
Configuration files should support parsing of environment variables

### ISSUE THREAD

**Issue by michaelryanmcneill** [sclorg/varnish-container#41]
Because OpenShift is extremely environment variable reliant, it would be ideal if we could add a simple process in the run script that would parse the configuration files for environment variables. This would allow for users to define environment variables for things like backend host and port, but could also be extended even further.

**Comment by phracek** [comment]
@michaelryanmcneill This issue is a bit out of scope for now. OpenShift itself does the same job as varnish. See https://github.com/sclorg/varnish-container/blob/master/6/README.md.

Testing varnish in OpenShift world is also suppressed and we do not have a plan to include it into test.

In case you have any use case for it, please bring it to this issue.
We do not have enough capacity to add environment variables to be more reliant.

Closing issue for now. Feel free to re-open it.
